/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import aurora.app.Main;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();
      //  assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
